experiment_name: cifar10_resnet
model: resnet
data:
  root: ./data
  max_train: 5000
  max_test: 1000
train:
  epochs: 3
  batch_size: 256
  lr: 0.001
  weight_decay: 0.0005
  optimizer: adamw
  scheduler: cosine
  grad_clip: 1.0
  label_smoothing: 0.0
misc:
  seed: 42
  num_workers: 0
  out_dir: ./runs
  resume: ""
  amp: true
  logging: none
  csv_logging: false
  log_confusion: false
  log_feature_maps: false
  log_gradcam: false
  log_every_n: 5

