run_name: 5day_meta_gru
seed: 1337

model:
  type: gru
  hidden_size: 128
  num_layers: 1
  bidirectional: false
  dropout: 0.0
  horizon: 5

data:
  type: yahoo
  ticker: META
  period: 5y
  interval: 1d
  use_log_returns: true
  window: 60
  horizon: 5
  split: 0.8

train:
  epochs: 10
  batch_size: 128
  lr: 0.001
  clip_grad: 1.0
