run_name: stooq_apple_lstm
seed: 1337

model:
  type: lstm
  hidden_size: 128
  num_layers: 1
  bidirectional: false
  dropout: 0.0
  horizon: 20

data:
  type: stooq
  ticker: AAPL
  start_date: 2015-01-01
  end_date: 2025-01-01
  use_log_returns: true
  window: 120
  horizon: 20
  split: 0.8

train:
  epochs: 20
  batch_size: 128
  lr: 0.001
  clip_grad: 1.0
