run_name: yahoo_btc_gru
seed: 1337

model:
  type: gru
  hidden_size: 128
  num_layers: 1
  bidirectional: false
  dropout: 0.0
  horizon: 24

data:
  type: yahoo
  ticker: BTC-USD
  period: 3y
  interval: 1d
  use_log_returns: true
  window: 96
  horizon: 24
  split: 0.8

train:
  epochs: 15
  batch_size: 128
  lr: 0.001
  clip_grad: 1.0
